language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
cache: pip
install:
  - python setup.py install
  - cd test && pip install -r requirements.txt
script:
  - git clone https://github.com/sidgarimella/conveyor.git && cd conveyor && python -m unittest discover